name: testy
on:
  pull_request: {}
jobs:
  its_the_test_job:
      name: TestJob
      uses: actions/github-script@v3
      with:
         script: |
           if (!['develop', 'staging'].includes(github.event.pull_request.base.ref) || !github.event.pull_request.base.ref.startsWith('feat/') {
             core.setFailed("Base branch invalid");
           }
