name: testy
on:
  pull_request_target:
    types: [ opened, edited, labeled ]
jobs:
  its_the_test_job:
      name: TestJob
      runs-on: ubuntu-latest
      steps:
        - uses: dbkr/testworkflow@master
          with:
            ghToken: ${{ secrets.GITHUB_TOKEN }}
