name: testy
on:
  pull_request_target:
    types: [ opened, edited ]
jobs:
  its_the_test_job:
      runs-on: ubuntu-latest
      steps:
        - uses: matrix-org/allchange@dbkr/checkeraction
          with:
            ghtoken: ${{ secrets.GITHUB_TOKEN }}
